# Generated by Django 5.1.4 on 2024-12-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, default='https://i.ibb.co/dLT0Kxs/thecat.jpg', null=True),
        ),
    ]
